---
- name: Load distro-specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include: install.yml
  when: state != "absent"
- include: uninstall.yml
  when: state == "absent"
